# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f75dcc345e9c772f7123809fe88dcb4711e5568fef42a9d8f74d4778023d94adcba2f652bf4b5ee3a5f9e10de43b98ca762cc42f02819e0c8bbdd362d927dc1

test:
  secret_key_base: a4cb2749b4e3447ed356194749c01653a84b2001729e20dd694fb8601a1db72f6eeda7a2f856fa092e58d2564682ff4eb57ebb79f66153e1bcf99bf8a2297b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
